trigger:
  - none
pr:
  - none


parameters:
  - name: enviroment
    displayName: enviorment to deploy
    type: string
    default: sandbox
    values: 
      - dev
      - sandbox
      - test
      - prod
      
stages:
  - stage: stageTest
    displayName: stageTest
    jobs:
      - job: jobTest
        displayName: jobTest
        steps:
          - bash: |
              echo "This is testBranch"
          - task: Bash@3
            inputs:
              targetType: 'inline'
              script: |
                # Write your commands here
                
                echo 'Hello world'
