trigger:
  - none
pr:
  - none

resources:
  repositories:
    - repository: templates
      type: github
      name: hmcts/azure-devops-templates
      ref: refs/heads/master
      endpoint: hmcts

parameters:
  - name: enviroment
    displayName: enviorment to deploy
    type: string
    default: sandbox
    values: 
      - dev
      - sandbox
      - test
      - prod
      
stages:
  - stage: stageTest
    displayName: stageTest
    jobs:
      - job: jobTest
        displayName: jobTest
        steps:
          - bash: |
              echo "This is testBranch"

